.github/workflows/ci.yml

update ci job name to "check formatting & lint"

---

README.md
package.json

Update scripts readme

---

package-lock.json
package.json
src/app.ts

N/A
Use gzip compression to improve performance by reducing size of response body. See link for info:
https://expressjs.com/en/advanced/best-practice-performance.html#use-gzip-compression

feat: use gzip compression for performance

---

.vscode/launch.json
package.json

Fixes #9 
TODO: Update README.md

fix: update launch configuration to use ts-node

---

README.md

docs: remove deleted debug script from readme

---

src/app.ts

fix: fix import for pinohttp to match type definitions

---

package.json

chore: add script to generate code test coverage report

---

.vscode/extensions.json

chore: configure vscode workspace extension recommendations

---

.prettierignore
eslint.config.mjs

chore: clean up ignore files

---

.prettierignore

chore: delete empty .prettierignore

---

package-lock.json
package.json
tests/integration/404.hurl
tests/integration/health-check.hurl

test: add hurl for integration tests (#38)

---

.nvmrc

Add .nvmrc

---

.github/workflows/ci.yml

Reverts tabletop-generator/server#46

Revert "Dont push docker image on pr"

---

.github/workflows/ci.yml

Dont push docker image on pr

---

README.md

docs(README): add ci badge

---

Dockerfile

build: include tests/.htpasswd in build

---

README.md

docs(README): improve formatting, add docker info

---

.vscode/launch.json
package-lock.json
package.json
src/limiter.js
src/routes/api/index.js
src/routes/index.js

feat: create router to mount api endpoints on `/v1`

---

.vscode/settings.json
docs/api_specification.md

N/A
Created API specification detailing:

Create API Specification

---

Dockerfile
README.md
docs/api-specification.md
src/routes/index.js

Update GitHub URL

---

docs/api-specification.md
docs/data-model.md

Specification update

---

.dockerignore
.env.docker-compose
.vscode/settings.json
README.md
docker-compose.yml
docker/postgres/initdb/initdb.sql

Setup dev environment: MinIO, Postgres, pgAdmin

---

docs/api-specification.md
src/routes/api/assets/deleteById.js
src/routes/api/assets/get.js
src/routes/api/assets/getById.js
src/routes/api/assets/index.js
src/routes/api/assets/patchById.js
src/routes/api/assets/post.js
src/routes/api/collections/deleteById.js
src/routes/api/collections/get.js
src/routes/api/collections/getById.js
src/routes/api/collections/index.js
src/routes/api/collections/patchById.js
src/routes/api/collections/post.js
src/routes/api/comments/deleteById.js
src/routes/api/comments/get.js
src/routes/api/comments/index.js
src/routes/api/comments/patchById.js
src/routes/api/comments/post.js
src/routes/api/index.js
src/routes/api/users/getById.js
src/routes/api/users/index.js
src/routes/api/users/patch.js
src/routes/api/users/post.js

Create API structure with empty routes

---

docs/data-model.md

docs(data model): add user pfp url expiry column

---

.env.docker-compose
.github/workflows/ci.yml
.vscode/extensions.json
.vscode/settings.json
README.md
docker-compose.yml
docker/postgres/initdb/initdb.sql
docs/data-model.md
package-lock.json
package.json
prisma/schema.prisma
src/prisma.js

Create database initialization script, Set up Prisma ORM, Fix flaky CI

---

.github/workflows/ci.yml
docker-compose.ci.yml
docker-compose.yml

Automatically create MinIO bucket, Wait for MinIO bucket creation and Postgres to be ready before starting server

---

.github/workflows/ci.yml
docker-compose.ci.yml
docker-compose.yml

Remove-minio-webconsole-from-ci

---

.github/workflows/ci.yml

ci: print logs if service times out

---

.dockerignore
Dockerfile
docker/postgres/initdb/initdb.sql
prisma/schema.prisma

Generate Prisma Client in build, Update DB schema

---

.env.docker-compose

Fix invalid database URL in Docker Compose env file

---

docs/CONTRIBUTING.md

CONTRIBUTING.md update

---

src/model/user.js

Create function to get user data and latest profile picture url

---

package-lock.json
package.json
src/routes/api/users/getById.js
tests/integration/users-get.hurl

implemented retrieving users via userid endpoint(`GET /v1/users/:id`), which gets a user from the database if the user exists.
1.  Implemented GET /users/:id endpoint
- Get user information by id, if users exists 
2.  Integration test
-  Test for user data
-  Test for non-existing user ids
- Test for invalid user ids (not a number)
- Test for authorization
Closes #92 
* endpoint: GET /v1/users/:id
* authentication: required
* response: 200 with successful retrieval

Implement GET /v1/users/:id

---

.vscode/settings.json
src/model/asset.js
tests/integration/assets-post-bad-request.hurl
tests/integration/assets-post.hurl

Create function to get assets and latest image url

---

.vscode/settings.json
src/model/asset.js
src/model/data/aws/index.js

Implement delete asset function

---

docker/postgres/initdb/initdb.sql
prisma/schema.prisma
src/routes/api/collections/patchById.js
tests/integration/collections-patch.hurl

Implement PATCH /v1/collections/:collectionId

---

src/routes/api/collections/patchById.js
tests/integration/collections-patch.hurl

Format PATCH collections response to match API spec

---

src/model/collection.js
src/routes/api/collections/index.js
src/routes/api/collections/post.js
tests/integration/collections-post.hurl

POST collection implementation

post collection

---

src/model/collection.js
src/routes/api/collections/deleteById.js
tests/integration/collection-deletebyid.hurl

Implemented DELETE route for collection, allowing users to delete collections owned by them
1. Implemented DELETE /v1/collections/:id
* Delete collections with its id
Closes #70
* endpoints: DELETE /v1/collections/:id
* authentication: required 
* response: 200 if deleting is successful

Implement DELETE /v1/collections/:id

---

src/routes/index.js
tests/integration/assets-get-by-id.hurl

Add auth exception for all `GET` routes that start with `/v1/assets`

---

src/routes/api/assets/getCommentsById.js
src/routes/api/assets/post.js
src/routes/api/collections/post.js
src/routes/api/comments/deleteById.js

Improve logging consistency

---

Dockerfile
compose.integration.yaml
compose.yaml

N/A
- Update Docker images in Dockerfile and Compose files

Update Docker images
